EdtechFoundry/react-native-gifted-messenger

GiftedMessenger.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/3)
=> fix(android): prevent autocomplete from preprending the next sent message

GiftedMessenger.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/4)
=> feature: add possibility for custom row renderer

GiftedMessenger.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/5)
=> chore(input): add testIDs for sending message

GiftedMessenger.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/6)
=> feature(messages): defer message diffing to parent

GiftedMessenger.js, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/7)
=> feature: dynamically grow text input

ErrorButton.js, GiftedMessenger.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/8)
=> chore: replace GiftedSpinner with ActivityIndicator as we are using RN 0.28

src/MessageContainer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/9)
=> feature: allow to pass rowHasChanged as prop

package.json, src/GiftedChat.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/11)
=> fix: added missing lodash import

src/MessageContainer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/12)
=> refactor: add onChangeVisibleRows listener

src/Send.js
should not inherit container styles.
=> fix: send button style

README.md, src/GiftedChat.js
for #DIF-135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/15)
=> feat: add function for the suggestions rendering

package.json, src/GiftedChat.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/16)
=> fix: suggestions layout

example/CustomActions.js, src/Actions.js, src/Bubble.js, src/Composer.js, src/GiftedChat.js, src/MessageContainer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/18)
=> fix(chat): migrate to the React Native v0.42

package.json, src/GiftedChat.js
issue #DIF-438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/20)
=> fix(chat): fix the flash when activating the keyboard

src/GiftedChat.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/21)
=> chore: warn when input ref is invalid

src/GiftedChat.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/22)
=> fix: fix resetInputToolbar functionality

README.md, src/GiftedChat.js, src/InputToolbar.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/24)
=> feat(input-toolbar): add option to hide the input toolbar

src/GiftedChat.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/28)
=> fix: remove should component update to prevent render-prevention

example/CustomActions.js, example/CustomView.js, package.json, src/Actions.js, src/Avatar.js, src/Bubble.js, src/Composer.js, src/Day.js, src/GiftedAvatar.js, src/GiftedChat.js, src/InputToolbar.js, src/LoadEarlier.js, src/Message.js, src/MessageContainer.js, src/MessageImage.js, src/MessageText.js, src/Send.js, src/Time.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/30)
=> fix propTypes

src/Composer.js, src/Constants.js, src/GiftedChat.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/33)
=> feat(composer): expose composer constants

README.md, package.json, src/GiftedChat.js, src/MessageContainer.js
Relates to #DIF-1997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/34)
=> feat(message-container): use flatlist instead of listview

package.json, src/Day.js, src/GiftedChat.js, src/Time.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/36)
=> fix: update moment and change imports to support RN 0.49

src/GiftedChat.js, src/Send.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/37)
=> feat(send): the restriction mechanism for send message

src/MessageContainer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/40)
=> fix(performance): do not extend extra data
